# Generated by Django 6.0.5 on 2026-06-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('PENDENTE', 'Pendente'), ('EM_PREPARACAO', 'Em Preparação'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20),
        ),
    ]
