# Generated by Django 6.0.5 on 2026-06-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
