# Generated by Django 6.0.5 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]